### PR TITLE
groupName support all language and replace special chars

### PR DESCRIPTION
**Pull request by jiangzhuo**
can match all language and filter special chars

### CODE REVIEW

**Comment by nswbmw** [comment]
👍

**Comment by luin** [comment]
starwars-star-wars-the-force-awakens-bb-8-3o7abB06u9bNzA8lu8

**Comment by jiangzhuo** [comment]
@luin @nswbmw 说个无关的，你们还招人吗？

**Comment by luin** [comment]
@jiangzhuo 招，来来来。把简历给 @nswbmw 让他领推荐奖 😆

**Pull request closed without merging**
